name: Compile

on:
  push:
    branches: [ "legacy" ]

jobs:
  windows:
    name: Windows (MSYS2)

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
    - name: Fetch Dependencies
      run: pacman -S --noconfirm unzip make git mingw-w64-i686-gcc mingw-w64-x86_64-gcc mingw-w64-i686-glew mingw-w64-x86_64-glew mingw-w64-i686-SDL2 mingw-w64-i686-SDL mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL python3 mingw-w64-x86_64-curl mingw-w64-x86_64-jsoncpp
    - name: Build
      run: make
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: saturn-${{ github.run_number }}-${{ github.job }}
        path: D:\a\Saturn\Saturn\build\us_pc\

  linux:
    name: Linux

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Fetch Dependencies
      run: sudo apt install build-essential git python3 libglew-dev libsdl2-dev curl libcurl4-gnutls-dev libjsoncpp-dev
    - name: Build
      run: make
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: saturn-${{ github.run_number }}-${{ github.job }}
        path: /home/runner/work/Saturn/Saturn/build/us_pc
